<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sportshub</title>
<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
<link rel="icon" type="<?php echo base_url();?>images/favicon" href="images/favicon.ico" />
<link href="<?php echo base_url();?>css/style.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url();?>css/jquery-confirm.css" rel="stylesheet">
<!--navigation-->
<link rel="stylesheet" href="<?php echo base_url();?>css/responsive-nav.css" />
<script type="text/javascript" src="<?php echo base_url();?>js/jquery.js"></script>
<script src="<?php echo base_url();?>js/responsive-nav.js" type="text/javascript"></script>
<!--navigation-->
<?php include('google_analytics.php')?>
</head>

<body> 
<div id="wrapper">
     <div id="header">
     	  <div class="container">
          	   <div class="logo"><a href="<?php echo base_url();?>"><img src="images/logo.png" /></a></div>
               <!--<div class="header_right"> <span class="nav_title">Sports Fans:</span>
                <div class="menu">
                  <div class="nav-1 nav-collapse">
                    <ul id="main-menu" class="sm sm-blue">
                      <li><a href="<?php echo base_url();?>app" >PERSONAL PLANNER</a></li>
                      <li><a href="<?php echo base_url();?>recommendbar">Recommend a Bar</a></li>
                      <li><a href="<?php echo base_url();?>quiz">QUIZ</a></li>
                      <li class="devider"></li>
                      <li><a href="<?php echo base_url();?>app/signup">signup</a> </li>
                      <li><a href="<?php echo base_url();?>app/login">login</a> </li>
                    </ul>
                  </div>
                </div>
              </div>--><!--close header_right-->
          </div><!--close container-->
     </div><!--close header-->
     
     <div id="content">
     	  <div class="section1" >
          	   <div class="container">
               		<div class="row">
                        <div class="terms_text">
                             <h2>Terms and Conditions</h2>
                             <ul>
                                <li>Competition details form part of these terms and conditions.</li>
                                <li>Entry is open to all except employees (and their families) of Sportshub365 LTD, 
                                its printers and agents, the suppliers <br/> of the prizes and any other companies associated with the competitions.</li>
                                <li>The entrant(s) must be aged 18 or over.</li>
                                <li>To administer a contest, promotion, survey or other site feature.</li>
                                <li>Proof of identity and age may be required.</li>
                                <li>Use of a false name or address will result in disqualification.</li>
                                <li>All entries must be made directly by the person entering the competition.</li>
                                <li>Entries made online using methods generated by a script, macro or the use of automated devices will be void.</li>
                                <li>Only Valid Venues will be accepted in the draw.</li>
                                <li>No responsibility can be accepted for entries lost, delayed or corrupted, or due to computer error in transit.</li>
                                <li>The prizes are as stated, are not transferable to another individual and no cash or other alternatives will be offered.</li>
                                <li>The winner(s) is(are) responsible for expenses and arrangements not specifically included in the prizes, including any <br/>necessary travel documents, passports and visas.</li>
                                <li>Prizes are subject to availability and the prize suppliers' terms and conditions.</li>
                                <li>The promoters reserve the right to amend or alter the terms of competitions and reject entries from entrants not entering <br/>into the spirit of the competition.</li>
                                <li>In the event of a prize being unavailable, the promoter reserves the right to offer an alternative prize of equal or greater value.</li>
                                <li>The winner(s) agree(s) to the use of their name, photograph and disclosure of county of residence and will cooperate with any other <br/> reasonable requests by Sportshub365 relating to any post-winning publicity.</li>
                                <li>Unless stated otherwise the winner(s) will be drawn at random from all correct entries received by the closing date stated within <br/> the promotional material.</li>
                                <li>Reasonable efforts will be made to contact the winner(s). If the winner(s) cannot be contacted, or are unable to comply with these <br/> terms and conditions, the Promoter reserves the right to offer the prize to the next eligible entrant drawn at random, or in the <br/>event that the promotion is being judged the Promoter reserves the right to offer the prize to the runner(s)-up selected by the same judges.</li>
                                <li>Confirmation of the prize will also be made in writing to the winner(s).</li>
                                <li>Failure to respond and/or provide an address for delivery, or failure to meet the eligibility requirements may result in forfeiture of the prize.</li>
                                <li>Where applicable, the decision of the judges is final based on the criteria set out in the promotion and no correspondence will be entered into over this decision.</li>
                                <li>Competitions may be modified or withdrawn at any time.</li>
                                <li>The provider of the prize is specified within the promotional material.</li>
                                <li>The Promoter is Sportshub365 Ltd, info@sportshub365.com</li>
                                <li>In the event of a discrepancy between these standard terms and conditions and the details in the promotional material (or any other terms and conditions provided/referred to at the time of entry), the details of the promotional material (and any other terms and conditions provided/referred to at the time of entry) shall prevail.</li>
                             </ul>
                        </div>
                        <!--<div class="feature_image"><img src="images/img1.png" /></div>-->
                    </div>
               </div><!--close container-->
          </div><!--close section1-->
         <div class="section5">
               		<span class="prev2"><a href="<?php echo base_url();?>venue">VENUES</a></span>
                    <span class="next2"><a href="<?php echo base_url();?>sportsfans">Sports Fans</a></span>
          </div><!--close section5-->
     </div><!--close content-->
     
     <div id="footer">
     	  <div class="container">
          	   <div class="logo_footer"><a href="<?php echo base_url();?>"><img src="images/logo.png" /></a></div>
               <p>contact us at <a href="mailto:info@sportshub365.com">info@sportshub365.com</a> <span style="white-space:nowrap;">&nbsp;&nbsp;+44 208 705 0525</span></p>
          </div><!--close container-->
     </div><!--close footer-->
      
</div><!--close wrapper-->
<script type="text/javascript" src="<?php echo base_url();?>js/jquery.smartmenus.js"></script>
<script type="text/javascript">
/*$(function() {
$('#main-menu').smartmenus({
subMenusSubOffsetX: 1,
subMenusSubOffsetY: -8
});
});*/
</script>

<link href="<?php echo base_url();?>css/sm-core-css.css" rel="stylesheet" type="text/css" />
<link href="<?php echo base_url();?>css/sm-blue.css" rel="stylesheet" type="text/css" /> 
<script type="text/javascript">
//var navigation1 = responsiveNav(".nav-1");
</script>
</body>
</html>
